export const NEW_ACTIVE_PLAYER = 'NEW_ACTIVE_PLAYER';
export const INCREASE_P1_COUNT = 'INCREASE_P1_COUNT';
export const INCREASE_P2_COUNT = 'INCREASE_P2_COUNT';

export const START_PLAY = 'START_PLAY';
export const TIMER_INTERVAL = 'TIMER_INTERVAL';
